services:
  research-nexus:
    image: research-nexus:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/research_nexus
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1906
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:latest
    container_name: research-nexus-redis
    ports:
      - "6379:6379"

